model_list:
  - model_name: os.environ/GEMINI_MODEL_NAME
    litellm_params:
      model: os.environ/GEMINI_MODEL_NAME
      api_key: os.environ/GEMINI_API_KEY_1
      # api_base: os.environ/GEMINI_API_BASE
      rpm: 10

  - model_name: os.environ/GEMINI_MODEL_NAME
    litellm_params:
      model: os.environ/GEMINI_MODEL_NAME
      api_key: os.environ/GEMINI_API_KEY_2
      # api_base: os.environ/GEMINI_API_BASE
      rpm: 10

  - model_name: os.environ/GEMINI_MODEL_NAME
    litellm_params:
      model: os.environ/GEMINI_MODEL_NAME
      api_key: os.environ/GEMINI_API_KEY_3
      # api_base: os.environ/GEMINI_API_BASE
      rpm: 10
      tpm: 250000

  - model_name: os.environ/GEMINI_MODEL_NAME
    litellm_params:
      model: os.environ/GEMINI_MODEL_NAME
      api_key: os.environ/GEMINI_API_KEY_4
      # api_base: os.environ/GEMINI_API_BASE
      rpm: 10
      tpm: 250000

  - model_name: os.environ/GEMINI_MODEL_NAME
    litellm_params:
      model: os.environ/GEMINI_MODEL_NAME
      api_key: os.environ/GEMINI_API_KEY_5
      # api_base: os.environ/GEMINI_API_BASE
      rpm: 10
      tpm: 250000

litellm_settings:
    drop_params: true